version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/server

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStop:
    - location: /opt/codedeploy-agent/deployment-root/ce899306-41ba-45d9-a99d-93b4903d3412/d-69YPWWV2Y/deployment-archive/server_stop.sh
      timeout: 20
      runas: ec2-user
  ApplicationStart:
    - location: /opt/codedeploy-agent/deployment-root/ce899306-41ba-45d9-a99d-93b4903d3412/d-69YPWWV2Y/deployment-archives/erver_start.sh
      timeout: 20
      runas: ec2-user
  ValidateService:
    - location: /opt/codedeploy-agent/deployment-root/ce899306-41ba-45d9-a99d-93b4903d3412/d-69YPWWV2Y/deployment-archive/server_validate.sh
      timeout: 60
      runas: ec2-user