version: 0.1
environment_variables:
    plaintext:
        S3_BUCKET: "globati.com"
        BUILD_ENV: "prod"
phases:
  install:
    commands:
    - echo '*********************** install phase'
  build:
    commands:
      - echo '******************** installing maven'
      - ls
      - mvn install -f master/pom.xml
      - mkdir api/target/scripts
      - mv appspec.yml api/target
      - mv server_start.sh api/target/scripts
      - mv server_stop.sh api/target/scripts
      - mv server_validate.sh api/target/scripts
  post_build:
    commands:
      - echo  '*********************************** Finishing build'
artifacts:
  files:
    - 'application.jar'
    - 'appspec.yml'
    - 'scripts/server_start.sh'
    - 'scripts/server_stop.sh'
    - 'scripts/server_validate.sh'
  base-directory: 'api/target'