version: 0.1
environment_variables:
    plaintext:
        S3_BUCKET: "globati.com"
        BUILD_ENV: "prod"
phases:
  install:
    commands:
    - echo '*********************** install phase'
  build:
    commands:
      - echo '******************** installing maven'
      - ls
      - ls master
      - cd master
      - mvn install
  post_build:
    commands:
      - echo  '*********************************** Finishing build'
