version: 0.1
environment_variables:
    plaintext:
        S3_BUCKET: "globati.com"
        BUILD_ENV: "prod"
phases:
  install:
    commands:
    - echo '*********************** install phase'
  build:
    commands:
      - echo '******************** installing maven'
      - ls
      - mvn install -f master/pom.xml
      - mv app spec.yml.zip api/target
  post_build:
    commands:
      - echo  '*********************************** Finishing build'
artifacts:
  files:
    - 'application.jar'
    - 'appspec.yml.zip'
  base-directory: 'api/target'