version: 0.1
environment_variables:
    plaintext:
        S3_BUCKET: "globati.com"
        BUILD_ENV: "prod"
phases:
  install:
    commands:
    - echo '*********************** install phase'
  build:
    commands:
      - echo '******************** installing maven'
      - ls
      - ls master
      - echo '****************** zipping appspec.yml'
      - zip appspec.yml.zip appspec.yml
      - mvn install -f master/pom.xml
  post_build:
    commands:
      - echo  '*********************************** Finishing build'
artifacts:
  files:
    - 'application.jar'
  base-directory: 'api/target'