package com.globati.utildb;

import java.util.UUID;

/**
 * Created by daniel on 4/8/17.
 */
public class FacebookUserId {

    /**
     * Creates a globati username by taking the facebook users real name, and adding 4 random numbers and letters to it.
     *
     * This method is vulnerable because it does not check that the created globati username exists already in the database.
     *
     * Therefore if the globati username generated by this method exists in the database, then an errow will be thrown
     *But I am pretty sure this will be handled as if a person creating a profile creates a profile that already exists.
     *
     * @param username
     * @return
     */
    public static String generateFacebookUserId(String username){
        String uid = UUID.randomUUID().toString();
        username+=uid.substring(9,13);
        return username;
    }

}
